<?php
/**
 * @file
 * multismtpconfignode.features.field_instance.inc
 */

/**
 * Implements hook_field_default_field_instances().
 */
function multismtpconfignode_field_default_field_instances() {
  $field_instances = array();

  // Exported field_instance: 'node-multismtp_config-field_smtp_allow_html'.
  $field_instances['node-multismtp_config-field_smtp_allow_html'] = array(
    'bundle' => 'multismtp_config',
    'default_value' => array(
      0 => array(
        'value' => 1,
      ),
    ),
    'deleted' => 0,
    'description' => '',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'module' => 'list',
        'settings' => array(
          'field_formatter_class' => '',
        ),
        'type' => 'list_default',
        'weight' => 7,
      ),
      'teaser' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 0,
      ),
    ),
    'entity_type' => 'node',
    'field_name' => 'field_smtp_allow_html',
    'label' => 'Allow Html',
    'required' => 1,
    'settings' => array(
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'options',
      'settings' => array(),
      'type' => 'options_buttons',
      'weight' => 16,
    ),
  );

  // Exported field_instance: 'node-multismtp_config-field_smtp_email'.
  $field_instances['node-multismtp_config-field_smtp_email'] = array(
    'bundle' => 'multismtp_config',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => '',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'module' => 'text',
        'settings' => array(
          'field_formatter_class' => '',
        ),
        'type' => 'text_default',
        'weight' => 8,
      ),
      'teaser' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 0,
      ),
    ),
    'entity_type' => 'node',
    'field_name' => 'field_smtp_email',
    'label' => 'Sender E-mail',
    'required' => 1,
    'settings' => array(
      'text_processing' => 0,
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'text',
      'settings' => array(
        'size' => 60,
      ),
      'type' => 'text_textfield',
      'weight' => 14,
    ),
  );

  // Exported field_instance: 'node-multismtp_config-field_smtp_login'.
  $field_instances['node-multismtp_config-field_smtp_login'] = array(
    'bundle' => 'multismtp_config',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => 'Leave blank if your SMTP server does not require authentication.',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'module' => 'text',
        'settings' => array(
          'field_formatter_class' => '',
        ),
        'type' => 'text_default',
        'weight' => 3,
      ),
      'teaser' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 0,
      ),
    ),
    'entity_type' => 'node',
    'field_name' => 'field_smtp_login',
    'label' => 'SMTP Login',
    'required' => 0,
    'settings' => array(
      'text_processing' => 0,
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'text',
      'settings' => array(
        'size' => 60,
      ),
      'type' => 'text_textfield',
      'weight' => 6,
    ),
  );

  // Exported field_instance: 'node-multismtp_config-field_smtp_name'.
  $field_instances['node-multismtp_config-field_smtp_name'] = array(
    'bundle' => 'multismtp_config',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => 'If set this sender name will be forced over sender name passed from other modules.',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'module' => 'text',
        'settings' => array(
          'field_formatter_class' => '',
        ),
        'type' => 'text_default',
        'weight' => 9,
      ),
      'teaser' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 0,
      ),
    ),
    'entity_type' => 'node',
    'field_name' => 'field_smtp_name',
    'label' => 'Sender Name',
    'required' => 0,
    'settings' => array(
      'text_processing' => 0,
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'text',
      'settings' => array(
        'size' => 60,
      ),
      'type' => 'text_textfield',
      'weight' => 15,
    ),
  );

  // Exported field_instance: 'node-multismtp_config-field_smtp_password'.
  $field_instances['node-multismtp_config-field_smtp_password'] = array(
    'bundle' => 'multismtp_config',
    'default_value' => array(
      0 => array(
        'password_field' => array(
          'password_field' => NULL,
        ),
      ),
    ),
    'deleted' => 0,
    'description' => '',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'module' => 'password_field',
        'settings' => array(
          'field_formatter_class' => '',
        ),
        'type' => 'password_field_formatter',
        'weight' => 4,
      ),
      'teaser' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 0,
      ),
    ),
    'entity_type' => 'node',
    'field_name' => 'field_smtp_password',
    'label' => 'SMTP Password',
    'required' => 0,
    'settings' => array(
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 0,
      'module' => 'password_field',
      'settings' => array(),
      'type' => 'password_field',
      'weight' => 7,
    ),
  );

  // Exported field_instance: 'node-multismtp_config-field_smtp_port'.
  $field_instances['node-multismtp_config-field_smtp_port'] = array(
    'bundle' => 'multismtp_config',
    'default_value' => array(
      0 => array(
        'value' => 25,
      ),
    ),
    'deleted' => 0,
    'description' => '',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'module' => 'number',
        'settings' => array(
          'decimal_separator' => '.',
          'field_formatter_class' => '',
          'prefix_suffix' => TRUE,
          'scale' => 0,
          'thousand_separator' => '',
        ),
        'type' => 'number_integer',
        'weight' => 1,
      ),
      'teaser' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 0,
      ),
    ),
    'entity_type' => 'node',
    'field_name' => 'field_smtp_port',
    'label' => 'SMTP Port',
    'required' => 1,
    'settings' => array(
      'max' => '',
      'min' => '',
      'prefix' => '',
      'suffix' => '',
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 0,
      'module' => 'number',
      'settings' => array(),
      'type' => 'number',
      'weight' => 4,
    ),
  );

  // Exported field_instance: 'node-multismtp_config-field_smtp_protocol'.
  $field_instances['node-multismtp_config-field_smtp_protocol'] = array(
    'bundle' => 'multismtp_config',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => '',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'module' => 'list',
        'settings' => array(
          'field_formatter_class' => '',
        ),
        'type' => 'list_default',
        'weight' => 2,
      ),
      'teaser' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 0,
      ),
    ),
    'entity_type' => 'node',
    'field_name' => 'field_smtp_protocol',
    'label' => 'SMTP Encryption',
    'required' => 1,
    'settings' => array(
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'options',
      'settings' => array(
        'apply_chosen' => '',
      ),
      'type' => 'options_select',
      'weight' => 5,
    ),
  );

  // Exported field_instance: 'node-multismtp_config-field_smtp_server'.
  $field_instances['node-multismtp_config-field_smtp_server'] = array(
    'bundle' => 'multismtp_config',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => 'The FQDN or IP of the SMTP server',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'module' => 'text',
        'settings' => array(
          'field_formatter_class' => '',
        ),
        'type' => 'text_default',
        'weight' => 0,
      ),
      'teaser' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 0,
      ),
    ),
    'entity_type' => 'node',
    'field_name' => 'field_smtp_server',
    'label' => 'SMTP Server',
    'required' => 1,
    'settings' => array(
      'text_processing' => 0,
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'text',
      'settings' => array(
        'size' => 60,
      ),
      'type' => 'text_textfield',
      'weight' => 3,
    ),
  );

  // Translatables
  // Included for use with string extractors like potx.
  t('Allow Html');
  t('If set this sender name will be forced over sender name passed from other modules.');
  t('Leave blank if your SMTP server does not require authentication.');
  t('SMTP Encryption');
  t('SMTP Login');
  t('SMTP Password');
  t('SMTP Port');
  t('SMTP Server');
  t('Sender E-mail');
  t('Sender Name');
  t('The FQDN or IP of the SMTP server');

  return $field_instances;
}
